language: java
install: true
jdk:
  - openjdk8
addons:
  sonarcloud:
    organization: "cesto93"
    token: $SONAR_TOKEN
script:
  - mvn clean verify sonar:sonar - Pcoverage
  #- mvn sonar:sonar -Pcoverage -Dsonar.projectKey=cesto93_TicketRetriever -Dsonar.organization=cesto93 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
#- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=cesto93_TicketRetriever
#  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar 
# the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  #- mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=cesto93_TicketRetriever
